app = "rotas-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Permitindo que a JVM use mais memória, com uma margem de segurança.
  JAVA_OPTS = "-Xms256m -Xmx768m" 

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true # Boa prática para forçar HTTPS

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Dando mais tempo para a aplicação iniciar
  [[services.http_checks]]
    interval = "30s"
    timeout = "15s"
    grace_period = "180s" 
    method = "get"
    path = "/actuator/health"
    protocol = "http"

# --- A MUDANÇA PRINCIPAL ESTÁ AQUI ---
[resources]
  # A CPU continua a mesma do plano gratuito
  # A memória foi aumentada para 1GB
  memory = "1024" 
