app = "rotas-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Mantemos a JVM com memória suficiente
  JAVA_OPTS = "-Xms256m -Xmx768m" 

# --- MUDANÇA NA ESTRATÉGIA DE CHECK ---
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Usaremos apenas o TCP check, que é mais tolerante
  # O grace_period aqui é respeitado de forma diferente
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "120s" # Vamos tentar 2 minutos aqui

# Mantemos a memória em 1GB
[resources]
  memory = "1024"
