app = "rotas-api"
primary_region = "gru" # São Paulo - melhor latência no Brasil

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
JAVA_OPTS = "-Xms256m -Xmx512m" # limita memória no plano gratuito

[[services]]
internal_port = 8080
processes = ["app"]

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "30s"
method = "get"
path = "/actuator/health"

[resources]
cpu = "shared"
memory = "512"
